### ISSUE TITLE
Can't load the addon.

### ISSUE THREAD

**Issue by jasonleft** [zhangyuanwei/node-images#101]
node -v 
7.0.0
boss来解决一下不能加载插件报错啊！

**Comment by pickTan** [comment]
node -v
v6.9.1
Can't load the addon.
boss来解决一下不能加载插件报错啊！
同求啊啊啊啊啊啊啊啊 ！！！！！！！！！！！！！！

**Comment by jasonleft** [comment]
@pickTan 亲测，目前最新LTS版本 6.9.2，配最新的node-images可用，大概看了下报错的目录，应该是针对每个版本的 nodejs写了js bindings，最新的7.0版本没写的吧

**Comment by pickTan** [comment]
最新版本是哪个。 我这边是image@3.0版本 但是不行。

**Comment by pickTan** [comment]
CentOS 6.5 linuxX64 v6.9.1 Can't load the addon. 
 哥 你能写个js bindings 咩 [期待脸]

**Comment by jasonleft** [comment]
表示完全不会写，我的是win7 x64位的，可以跑nodejs 6.9.2

**Comment by pickTan** [comment]
你最终运行还是会上linux，最终还是通不过。我看作者已经不管这个插件了

**Comment by xiangshouding** [comment]
Linux 哪个版本，哪个内核的？

**Comment by pickTan** [comment]
CentOS: 6.5 
Linux slaver01 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
node:v6.9.1

**Comment by pickTan** [comment]
是否编译一个"GLIBC_2.14"就可以了？

**Comment by xiangshouding** [comment]
你可以把你的机器给我，我帮你编译。

**Comment by jasonleft** [comment]
@xiangshouding 大神，nodejs 7.0.0 win7 x64位报错，是不是因为没有写js bindings ？

**Comment by pickTan** [comment]
@xiangshouding  哥  你有帮我编译吗？急着用

**Comment by taoqf** [comment]
國人的東西皆類此乎？不靠譜呀。

**Comment by xiangshouding** [comment]
54218bb7a7b574faaedd25010bd71acd3a20c143

其他系统的慢慢来，我还得找机器。。

**Comment by zhiguan-hanks** [comment]
node v 4.6.1
Error: Can't load the addon.
The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\D:\work\node_modules\images\bindings\win32\x64\6.0.0\binding.node........

**Comment by wv1124** [comment]
`✘ wv@iMac-WV  ~/work/d2papp/faster   br-3.0 ●  NODE_ENV=development babel-node ./app.js
/Users/wv/work/d2papp/faster/node_modules/images/binding.js:61
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);
^

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/Users/wv/work/d2papp/faster/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/wv/work/d2papp/faster/node_modules/images/index.js:32:15)
 ✘ wv@iMac-WV  ~/work/d2papp/faster   br-3.0 ●  node -v
v7.4.0
 wv@iMac-WV  ~/work/d2papp/faster   br-3.0 ●  npm -v
3.10.9`

**Comment by boban984** [comment]
Not usable on Windows 10

node -v
v7.2.1

npm -v
3.10.10

**Comment by fengyh13** [comment]
@wv1124 你好，你的node 7.x版本能跑这个模块吗，为什么我的更新了也没办法跑

**Comment by xiangshouding** [comment]
Windows & Linux 的 Node 7.x 版本还没有编译。

**Comment by Diluka** [comment]
node -v
v7.9.0
"images": "^3.0.0"
Can't load the addon.
macOS 10.12.4 
boss来解决一下不能加载插件报错啊！

**Comment by chengwubin** [comment]
node -v
v6.9.4
npm -v
4.5.0
win10
Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: Cannot find module './bindings/win32/x64/6.0.0/binding.node
