### ISSUE TITLE
应该让save()支持无参数

### ISSUE THREAD

**Issue by zengleyi** [zhangyuanwei/node-images#102]
比如一个图片文件只改变大小，不需要另存为其他图片文件，好像images(path).resize(1000)不行，但是如果必须要写成images(path).resize(1000).save(path)，就有些太傻了，同样的路径，文件原地不动得写两次。希望save()能支持无参数，直接images(path).resize(1000).save()就能让图片改变尺寸之后保存为自身。

**Comment by itkdqwzero** [comment]
用encode函数
.size(300).encode("jpg")
返回一个Buffer对象
