### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by tianez** [zhangyuanwei/node-images#103]
E:\SoftWare\www\dszb\app\node_modules\.3.0.0@images\binding.js:61
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);
^

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (E:\SoftWare\www\dszb\app\node_modules\.3.0.0@images\binding.js:61:7)

**Comment by QiPg** [comment]
这是node版本的问题 建议使用6.10.1的

**Comment by xqq965** [comment]
怎么解决啊，我也遇到了

**Comment by xiangshouding** [comment]
应该是二进制扩展不支持你的系统。

**Comment by zikuai** [comment]
同问，怎么解决，我也遇到了，我是8.1.3

**Comment by souljessi** [comment]
我也想问，node 8.0以上就报这个错，能不能解决下

**Comment by xqq965** [comment]
好像 新版本已经支持到node 8.0 测试的时候10.X 还不行
