### ISSUE TITLE
期待node7的编译包啊，node8都快要出来了啊！！

### ISSUE THREAD

**Issue by wj008** [zhangyuanwei/node-images#104]
期待node7的编译包啊，node8都快要出来了啊。
希望博主有时间的时候可以编译一下 node7 的window 64版本 其他版本我想大伙都会在Linux上重建，window的编译似乎比较困难一点，32位的其实可以晚一点，估计现在开发者大多不用 32位的吧，而node7 在开发中主要用到 async await 不得不升级到node7  而node6 没有支持，不然降级开发也可以。
迫切期待.....

**Comment by caihuattkl** [comment]
我的node版本v7.4.0   无法使用啊！！！Can't load the addon.

**Comment by wj008** [comment]
没办法 自己动手丰衣足食了，node7 的window 64版本
编译文件 https://github.com/wj008/node7.xx-images

**Comment by sicwolf** [comment]
https://github.com/wj008/node7.xx-images，我的系统是64位win7，你编译出来的node-image在我的环境中不能被识别。
能不能把编译的详细步骤列出来，我自己的编译总是报错，感觉是node-images依赖的库的版本没取对
不胜感激！

**Comment by wj008** [comment]
@sicwolf 你安装一下 vs2015或者vs2017的运行时在试试！如果还不行，我改天把编译过程整理一下！

**Comment by xiangshouding** [comment]
+images@3.0.1
