### ISSUE TITLE
binding.node linux x64 node 7.v

### ISSUE THREAD

**Issue by kainonly** [zhangyuanwei/node-images#105]
[binding.zip](https://github.com/zhangyuanwei/node-images/files/901566/binding.zip)
编译了一份linux x64 node 7.v版本的binding.node分享给大家。

**Comment by qiushi2012** [comment]
linux x64 node的7.v的版本还没出来吧 @zhangtqx

**Comment by yajore** [comment]
@zhangtqx  我每次下载到50%左右就是无法下载了，如有时间麻烦发送一份到 yajore@163.com 邮箱，谢谢
