### ISSUE TITLE
图片质量问题

### ISSUE THREAD

**Issue by SunGg12138** [zhangyuanwei/node-images#107]
我用node-images，png和jpg合成图片时，我把质量调到最大，但是png图片上的文字也有点模糊，我该如何解决呢？

> var themeBuf = images(images(preWallpaper + wallpapers + '.jpg'), 0, 0, 1080, 1167)
		            .draw(images(preWidgets + widgets_previews + '.png'), 0, 0)
			    .draw(images(topLayer), 0, 0)
			    .encode('jpg', { operation: 100 });

**Comment by SunGg12138** [comment]
我的邮箱：sunjinguang@kuba.bz
期待您的邮件！

**Comment by wenye123** [comment]
我也发现了 裁剪的图片超级模糊 简直没法用

**Comment by xiangshouding** [comment]
给个样例看看？
