### ISSUE TITLE
binding.node for linux with node v8.x.x

### ISSUE THREAD

**Issue by smassin** [zhangyuanwei/node-images#110]
Binding.node for linux with node 8.x.x.

**Important: This binding does not support GIF.**

For whatever reason when I build the binding with GIF node crashes crashes with "Undefined symbol: reallocarray" so for now I disabled gif (to avoid the crash) until I can figure out what's wrong with it. JPG and PNG are tested to be working with this binding. If anyone knows why symbol error is happening please do share.

Enjoy :)

[binding.node.zip](https://github.com/zhangyuanwei/node-images/files/1102667/binding.node.zip)

**Comment by xiangshouding** [comment]
Thanks

**Comment by tc-imba** [comment]
I build the binding file supporting all addons @smassin 
[binding.node.tar.gz](https://github.com/zhangyuanwei/node-images/files/1236531/binding.node.tar.gz)

**Comment by xiangshouding** [comment]
8335d1b release v2.2.1
