### ISSUE TITLE
Where is the code of version 3.0.0 ?

### ISSUE THREAD

**Issue by nitriques** [zhangyuanwei/node-images#113]
On npm, there is https://www.npmjs.com/package/node-images which looks like the current master branch, but one minor patch ahead (2.2.1 instead of 2.2.0)

But there is also this https://www.npmjs.com/package/images which is version 3.0.0, but I can't find the code. This is the repo I've always used and stumble upon the other one.

Can we have an update on this mater ? I have a working version with [webp + numerous other improvements (like a distribution script)](https://github.com/DeuxHuitHuit/node-images/tree/webp), I'd like to send a PR, but I'd like to be based on the latest version of the code.

BTW, thanks for this software. It's been really useful and what to help make it even better. 🥇

**Comment by nitriques** [comment]
Ok thanks for pushing version 2.2.1, but https://github.com/zhangyuanwei/node-images/tree/3.0.0 lags behind. On why commit/branch should I base my PR ?

**Comment by nitriques** [comment]
I can help with many things if you want to give me write access to the repo and issue tracker....

**Comment by nitriques** [comment]
I will be contacting @npm on that matter if I do not have a response soon.

**Comment by xiangshouding** [comment]
+images@3.0.1

**Comment by nitriques** [comment]
@xiangshouding Thanks, but https://www.npmjs.com/package/node-images still lags behind. Why ?

But thanks, I see the code now, will send a huge PR soon.

If you want help for maintenance and github issues, please add me as a collaborator on the project. It could make everything a lot faster.

**Comment by xiangshouding** [comment]
please use images@3.0.1, node-images is clone.

**Comment by nitriques** [comment]
Ok thanks @xiangshouding 

You should consider publishing a new version on npm, telling people that `node-images` is deprecated.
