### ISSUE TITLE
 Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/app/taf/FileServer.FileServer/bin/src/node_modules/images/bindings/linux/x64/8.0.0/binding.node)

### ISSUE THREAD

**Issue by 813751** [zhangyuanwei/node-images#115]
Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/app/taf/FileServer.FileServer/bin/src/node_modules/images/bindings/linux/x64/8.0.0/binding.node)

**Comment by nitriques** [comment]
Which version of gcc ?

**Comment by DidoFitch** [comment]
https://github.com/zhangyuanwei/node-images/issues/94
