### ISSUE TITLE
[Bug]draw(img, x, y)方法的x,y不能为负数

### ISSUE THREAD

**Issue by RockyF** [zhangyuanwei/node-images#120]
经测试，如果坐标小于0，就会绘制失败，请修复。

**Comment by xiangshouding** [comment]
此处坐标没有负数的概念，OK ？

**Comment by RockyF** [comment]
画一张png上去，我只想画右下角的部分，那坐标不是会小于0吗！

**Comment by xiangshouding** [comment]
坐标是倒置的，左上角是原点(0,0)，向下 y，向右 x。

**Comment by RockyF** [comment]
我看了Image.cc的源码，发现`void PixelArray::Draw(PixelArray *src, size_t x, size_t y)`方法里，如果x或y 小于0，那么`if(x < dw && y < dh){`肯定为`false`，所以没有画出来。

**Comment by RockyF** [comment]
![image](https://user-images.githubusercontent.com/1643017/30464356-bb1c9368-9a03-11e7-9f6e-c264804c0c4d.png)
我想把圆的图画到方的图上难道不行吗？这样圆的图的坐标不是要小于0了吗！

**Comment by xiangshouding** [comment]
你可以先画方块，然后再画圆圈。

**Comment by RockyF** [comment]
圆和方只是举例。。。你可以试试，draw()如果坐标小于0会不会成功。

**Comment by xiangshouding** [comment]
@RockyF 当然不成功啊，就没有这样的坐标设定。你能不能去看看 convas 的坐标相关的知识再来讨论这个问题？

**Comment by RockyF** [comment]
意思就是说这个库在draw的时候坐标不能小于0？
怎么会没有这种需求呢？

**Comment by RockyF** [comment]
亲测，HTML5的canvas在draw的时候坐标**都能小于0**。意思就是说这个库在draw的时候坐标不能小于0？
**怎么会没有**这种需求呢？

**Comment by zhangyuanwei** [comment]
我知道啥意思了，看了下现在的代码

**Comment by RockyF** [comment]
亲测，HTML5的canvas在draw的时候坐标都能小于0。
你的意思就是说这个库在draw的时候坐标不能小于0？
怎么会没有这种需求呢？

**Comment by zhangyuanwei** [comment]
我知道 @RockyF 啥意思了：刚看了下现在的代码，
```cpp
    x = args[1]->Uint32Value();
    y = args[2]->Uint32Value();

    dst->pixels->Draw(src->pixels, x, y);
```
写的时候直接认为是正数了。。 -_- !!!

**Comment by xiangshouding** [comment]
我感觉没必要实现负坐标 @zhangyuanwei ，实现它搞毛？

**Comment by RockyF** [comment]
那是因为你 @xiangshouding  暂时没有这种需求而已，不能保证别人没有这种需求。

**Comment by zhangyuanwei** [comment]
@RockyF 现在改代码再编译发布有点麻烦，要是应急得话，可以用现有API做出来。就是先把圆形做裁剪，然后再画到矩形左上角上。
