### ISSUE TITLE
请问这个错误如何解决?

### ISSUE THREAD

**Issue by mxh861001** [zhangyuanwei/node-images#122]
执行draw时,报错如下该如何解决?
> /home/liu/.node-gyp/8.4.0/include/node/node_object_wrap.h:50: static T* node::ObjectWrap::Unw
rap(v8::Local<v8::Object>) [with T = Image]: Assertion `handle->InternalFieldCount() > 0' failed.

**Comment by xiangshouding** [comment]
save 你没有传参吧？

**Comment by xiangshouding** [comment]
代码贴出来看看

**Comment by KaneOne** [comment]
我遇到同样的问题：
const fs = require('fs');
const pify = require('pify');
const images = require('images');


images('1.png').draw('2.png',10,10).save('3.png')
