### ISSUE TITLE
Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/app/taf/FileServer.FileServer/bin/src/node_modules/images/bindings/linux/x64/8.0.0/binding.node)

### ISSUE THREAD

**Issue by Cshiyuan** [zhangyuanwei/node-images#123]
Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/app/taf/FileServer.FileServer/bin/src/node_modules/images/bindings/linux/x64/8.0.0/binding.node)

有低点的版本，不需要GLIBC_2.14的吗

**Comment by xiangshouding** [comment]
。。这个比较尴尬，Linux 环境下的兼容问题更闹心啊。

**Comment by loumt** [comment]
同问

**Comment by loumt** [comment]
console - Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/XXXXXX/node_modules/images/vendor/linux-x64-48/binding.node)

**Comment by loumt** [comment]
升级glibc,问题解决（make与make install 时间比较长），我保守升到2.15
CentOS release 6.8 
node 6.11.2

**Comment by loumt** [comment]
之前3.0.0没有问题的，为什么出3.0.1时会影响到3.0.0

**Comment by DidoFitch** [comment]
https://github.com/zhangyuanwei/node-images/issues/94
