### ISSUE TITLE
Electron最新版(1.7.9)自带的node.js(7.x)不能使用images模块

### ISSUE THREAD

**Issue by KanaHayama** [zhangyuanwei/node-images#126]
Error: imagesdoes not yet support your current environment: Windows 64-bit with Unsupported runtime (54)
7.x不是LTS，但Electron（electron.atom.io）又在用。用不了很让人头疼……

**Comment by xiangshouding** [comment]
自己编译一下？

**Comment by chenxiaochun** [comment]
```
Uncaught Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: The module '/Users/chenxiaochun/Downloads/electron-quick-start/node_modules/jdf-css-sprite/jdf-css-sprite/bindings/darwin/x64/7.0.0/binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```
我貌似也是遇到了相同的问题

**Comment by painty** [comment]
能提供下Windows下的编译方法吗？

**Comment by chenxiaochun** [comment]
@painty ,我是在网上看到过几种方法，使用`npm rebuild`或者`node-gyp`。可是在我的项目里没有尝试成功，你可以试试。

**Comment by lihang1870719** [comment]
mac上成功了，window一直报错啊

**Comment by lihang1870719** [comment]
@xiangshouding 你好，我按照说明重新编译windows的版本，提示下面的错误，如果可以，麻烦给点提示

Image.obj : error LNK2001: 无法解析的外部符号 "enum ImageState __cdecl rotate(st
ruct Pix
elArray *,struct PixelArray *,unsigned __int64)" (?rotate@@YA?AW4ImageState@@PE
AUPixelArray@@0_K@Z) [D:\work\demo\electron-quick-start\node_modules\node-image
s\build\binding.vcxproj]
giflib.lib(dgif_lib.obj) : error LNK2001: 无法解析的外部符号 reallocarray [D:\wo
rk\demo\
electron-quick-start\node_modules\node-images\build\binding.vcxproj]
D:\work\demo\electron-quick-start\node_modules\node-images\build\Release\bindin
g.node : fatal error LNK1120: 2 个无法解析的外部命令 [D:\work\demo\electron-quic
k-start\n
ode_modules\node-images\build\binding.vcxproj]

**Comment by liupishui** [comment]
https://github.com/electron/electron/blob/v0.37.2/docs/tutorial/using-native-node-modules.md#using-native-node-modules
`.\node_modules\.bin\electron-rebuild.cmd`
编译失败同求解决办法

**Comment by lihang1870719** [comment]
@liupishui  你可以试试node-canvas， 我用了这个库
