### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by king-king** [zhangyuanwei/node-images#127]
![_20171027163016](https://user-images.githubusercontent.com/8537319/32094991-2ac88220-bb34-11e7-8997-7a9213f854f3.png)

这个问题会导致运行时报_Image is not a constructor错误

**Comment by xiangshouding** [comment]
下载失败了嘛，肯定用不了。

**Comment by king-king** [comment]
为啥会出这个问题呢？我们好几个同事都遇到了这个问题

**Comment by king-king** [comment]
而且非常奇怪的是，我换了网络环境也不行，是不是你把文件删除了？

**Comment by xiangshouding** [comment]
@king-king 我查查，骚等。

**Comment by rainAgain** [comment]
我也遇到了这个问题，求解决

**Comment by isuoge** [comment]
6.10.0遇到相同问题，希望大大快点解决

**Comment by chengwubin** [comment]
npm rebuild images --force
npm WARN using --force I sure hope you know what you are doing.

> images@3.0.1 install F:\workspace\KO\Dtml\node_modules\images
> node ./scripts/install.js

Downloading binary from https://github.com/zhangyuanwei/node-images/releases/download/v3.
0.1/win32-x64-48_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/win
32-x64-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
images@3.0.1 F:\workspace\KO\Dtml\node_modules\images

**Comment by xiangshouding** [comment]
@rainAgain @chengwubin 试一下，编译了一个 48 的。

**Comment by rainAgain** [comment]
可以了，谢谢大佬 : )

**Comment by zhangweiyuan** [comment]
npm 安装的时候下面会出来一个链接，你直接把这个链接复制下来用迅雷下载，然后把下载的文件复制到目录内
![snipaste_2017-11-23_16-13-24](https://user-images.githubusercontent.com/9761347/33163418-622b47ee-d069-11e7-9ab7-23beb281a740.jpg)

**Comment by renxia** [comment]
@zhangweiyuan 迅雷也下载不到
这个有没有国内的镜像呢

**Comment by JTT5327** [comment]
https://github.com/zhangyuanwei/node-images/releases/download/v3.
0.1/win32-x64-48_binding.node
这个文件可以用迅雷下载下来，谢谢楼主
