### ISSUE TITLE
下载失败，好像是没这个文件

### ISSUE THREAD

**Issue by zhuweiyou** [zhangyuanwei/node-images#130]
在安装 3.0.1 的时候下载

```
Downloading binary from https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/darwin-x64-59_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/darwin-x64-59_binding.node": 

HTTP error 404 Not Found

```

**Comment by zhangweiyuan** [comment]
npm 安装的时候下面会出来一个链接，你直接把这个链接复制下来用迅雷下载，然后把下载的文件复制到目录内
![snipaste_2017-11-23_16-13-24](https://user-images.githubusercontent.com/9761347/33163418-622b47ee-d069-11e7-9ab7-23beb281a740.jpg)

**Comment by zhuweiyou** [comment]
@zhangweiyuan  我的是  `darwin-x64-59` 我去 release 里头看了，根本就没这个文件。直接访问是 404 的

**Comment by zhangweiyuan** [comment]
@zhuweiyou 
这里最高是57    https://github.com/zhangyuanwei/node-images/releases/tag/v3.0.1
你的59是从那里来的，要么你换成 57

**Comment by zhuweiyou** [comment]
@zhangweiyuan 哥，不是我 59 哪来的。是 install 的时候自动给我装的 59

**Comment by lisundy** [comment]
我也是一样的问题，自动安装59

**Comment by xiangshouding** [comment]
Windows | x86 & x64 | 0.9.11, 0.10, 0.12, 1, 2, 3, 4, 5, 6, 8
-- | -- | --
OSX | X64 | 0.9.11, 0.10, 0.12, 1, 2, 3, 4, 5, 6, 8
Linux* | x86 & x64 | 0.9.11, 0.10, 0.12, 1, 2, 3, 4, 5, 6, 8

麻烦看看支持列表。。

**Comment by zhuweiyou** [comment]
@xiangshouding 卧槽，原来是不支持 node 9。。。

**Comment by renxia** [comment]
@zhangweiyuan @xiangshouding @zhangyuanwei
可以发一份最新的 win32-x64-57_binding.node 到我邮箱里吗，各种方式都下载不到，感谢大佬们

lzwy0820@qq.com
