### ISSUE TITLE
node docker 镜像中安装报错

### ISSUE THREAD

**Issue by saas-plat** [zhangyuanwei/node-images#131]
> images@3.0.1 install /srv/saas-plat-usr/node_modules/images
> node ./scripts/install.js

Downloading binary from https://github.com/zhangyuanwei/node-images/releases/down                                                load/v3.0.1/linux_musl-x64-57_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3                                                .0.1/linux_musl-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

**Comment by zhangweiyuan** [comment]
npm 安装的时候下面会出来一个链接，你直接把这个链接复制下来用迅雷下载，然后把下载的文件复制到目录内
![snipaste_2017-11-23_16-13-24](https://user-images.githubusercontent.com/9761347/33163418-622b47ee-d069-11e7-9ab7-23beb281a740.jpg)

**Comment by NightFarmer** [comment]
遇到了同样的情况 不过我这边打印的是
https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/linux-x64-59_binding.node
这个404

**Comment by NightFarmer** [comment]
@zhangweiyuan 请问x64_后面跟的59这个数字有什么特殊含义呢
我看了release里确实没有这个文件, 这个该何解?

**Comment by stspqxl** [comment]
迅雷下载也是出错啊，这个怎么回事，不能把文件补一下？

我的是提示

https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/linux_musl-x64-57_binding.node

**Comment by xiangshouding** [comment]
@stspqxl 你用的系统的信息被改了呀，你用的是 https://www.musl-libc.org/ libc 的 linux，不支持，如果需要支持就编译一下吧。现在系统千奇百怪，无法提前全部预料到。

**Comment by shuaizhiwen** [comment]
https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/linux_musl-x64-57_binding.node 现在这个还是提示无法找到，无法在 docker 中运行这个
