### ISSUE TITLE
Ubuntu安装成功，但运行报错，啥原因呢～～

### ISSUE THREAD

**Issue by 79229788** [zhangyuanwei/node-images#132]
imagescould not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x
  - Linux 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.

**Comment by ugrg** [comment]
我这也是，按装成功，没有编译就过了。运行时报错，

**Comment by ugrg** [comment]
我是在windows下的。
