### ISSUE TITLE
编译的时候报以下404错误，发现没有linux-x64-59_binding.node 这个文件 

### ISSUE THREAD

**Issue by taodawn** [zhangyuanwei/node-images#136]
编译的时候报以下404错误，发现没有linux-x64-59_binding.node 这个文件 
需要做什么设置吗？我换了一台server编译，倒是可以编译过的，发现在那台好的Server上 下载的文件是/linux-x64-48_binding.node 

npm install images
> Downloading binary from https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/linux-x64-59_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/linux-x64-59_binding.node":
HTTP error 404 Not Found

**Comment by shiny** [comment]
```

> images@3.0.1 install /usr/src/app/node_modules/images
> node ./scripts/install.js

Downloading binary from https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/linux_musl-x64-57_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/linux_musl-x64-57_binding.node":

HTTP error 404 Not Found
```
