### ISSUE TITLE
我看api里的方法都是异步的，为什么没有操作完成的回调呢？

### ISSUE THREAD

**Issue by wuyanfei** [zhangyuanwei/node-images#137]
我看api里的方法都是异步的，为什么没有操作完成的回调呢？我如何在保存完图片后继续后续的逻辑

**Comment by xiangshouding** [comment]
API 设计确实没考虑同步异步的事情，都是同步接口。不需要回调，你是遇到什么问题了么？

**Comment by txhdqzy** [comment]
全是同步的接口那对 node 运行会有阻塞吧
