### ISSUE TITLE
missing darwin-x64-59_binding.node

### ISSUE THREAD

**Issue by tigercosmos** [zhangyuanwei/node-images#142]
Downloading binary from https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/darwin-x64-59_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/darwin-x64-59_binding.node":

**Comment by xiangshouding** [comment]
没编译 59 moduleid 的包，你可以尝试自己编译一下。

**Comment by tigercosmos** [comment]
可以教一下怎麼做嗎？ :)

**Comment by xiangshouding** [comment]
#45
