### ISSUE TITLE
请教下linux centos下安装报这个错怎么解决呢？

### ISSUE THREAD

**Issue by laiyiyi** [zhangyuanwei/node-images#149]
![image](https://user-images.githubusercontent.com/12541388/41410096-e963b8f4-700a-11e8-8557-6e6e16436005.png)

**Comment by xiangshouding** [comment]
目录没有权限，改一下权限就好了。

**Comment by laiyiyi** [comment]
还是不行呀
![image](https://user-images.githubusercontent.com/12541388/41462236-bf4f1c74-70c4-11e8-8e0b-0c680b40a3b9.png)

**Comment by laiyiyi** [comment]
@cench 这个问题了
![image](https://user-images.githubusercontent.com/12541388/42269680-663cb9e2-7fb1-11e8-88f3-8c14e6f741ed.png)

**Comment by cench** [comment]
切npm源 用淘宝源

**Comment by laiyiyi** [comment]
@cench 就是cnpm i的呀

**Comment by cench** [comment]
用 nrm 切 npm 淘宝源 不要用cnpm 试试

**Comment by laiyiyi** [comment]
@cench 先进入目录创建 linux-那个目录 之后手动给个 777 权限，之后再npm i 不是又重新覆盖了吗？

**Comment by laiyiyi** [comment]
...  把node版本降低，  才可以....

**Comment by cfz1005** [comment]
@laiyiyi 请用Node要用哪个版本才可以，我目前是v8.12.0，有问题

**Comment by laiyiyi** [comment]
8.2^就可以，不过不能pm2 启多个进程，那样会生成不了图片。单进程就没问题

**Comment by xiangshouding** [comment]
@laiyiyi 你是要实时进行处理图片么？
