### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _reallocarray

### ISSUE THREAD

**Issue by txhdqzy** [zhangyuanwei/node-images#150]
是否是对图片的类型有限制？只能用在 jpg 上面吗？

dyld: lazy symbol binding failed: Symbol not found: _reallocarray
  Referenced from: /Users/nickzhou/WebstormProjects/childfolio_family/node_modules/images/vendor/darwin-x64-57/binding.node
  Expected in: flat namespace

**Comment by xiangshouding** [comment]
jpg、gif、png 的 decode 都集成了，你是什么操作系统？

**Comment by IAIAE** [comment]
这个问题解决了么？
