### ISSUE TITLE
保存的图片自动旋转方向了，将竖向变成了横向

### ISSUE THREAD

**Issue by wangzongming** [zhangyuanwei/node-images#154]
图片纵横比4:3
图片尺寸3024 x 4032
图片大小4.9 MB

**Comment by wangzongming** [comment]
....

**Comment by loveJSON** [comment]
没毛病，我这边复现手机类型是小米MIX2
求解决方案

**Comment by xiangshouding** [comment]
为什么有这么个问题，把机型以及图片发一下？

**Comment by loveJSON** [comment]
您好：
bug复现场景：
手机类型为小米mix2
电脑端查看小米mix2拍摄的图片
宽为：2250px
高为：4000px
上传到服务端之后用image拿到的图片
宽为：4000px
高为：2250px

**Comment by wangzongming** [comment]
https://github.com/zhangyuanwei/node-images/issues/154#issuecomment-441506662 @xiangshouding 
我的是小米8
