### ISSUE TITLE
OS X 64-bit with Unsupported runtime

### ISSUE THREAD

**Issue by JulyMao** [zhangyuanwei/node-images#156]
imagesdoes not yet support your current environment: OS X 64-bit with Unsupported runtime
不支持MAC 64位吗？

**Comment by rogovdm** [comment]
Seems so :|

**Comment by cttaohua** [comment]
Error: imagesdoes not yet support your current environment: Linux 64-bit with Unsupported runtime (59)
linux都不支持，拜托不支持的话在markdown里边写出来，别浪费大家时间

**Comment by xiangshouding** [comment]
好的，浪费你时间了，表示非常抱歉。

cttaohua <notifications@github.com> 于2018年12月11日周二 下午4:09写道：

**Comment by zhuyuwaiting** [comment]
这个两年了还是不支持啊
