### ISSUE TITLE
compiler in node version 10+

### ISSUE THREAD

**Issue by ningzhiqun** [zhangyuanwei/node-images#162]
请问下，你在2015 年写的手动编译，在node 10以上版本还适用吗？因为生产环境无法支持node9一下版本。

**Comment by xiangshouding** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}     不太行了，正在适配                                                                                                                                                                        发送自我的 BlackBerry - 安全智能手机                                                                                                                                                                           发件人： notifications@github.com发送时间： 2018年12月17日 下午11:09收件人： node-images@noreply.github.com回复： reply@reply.github.com抄送： subscribed@noreply.github.com主题： [zhangyuanwei/node-images] compiler in node version 10+ (#162)  请问下，你在2015 年写的手动编译，在node 10以上版本还适用吗？因为生产环境无法支持node9一下版本。

**Comment by xiangshouding** [comment]
现在可以了
