### ISSUE TITLE
什么时候能支持node10+

### ISSUE THREAD

**Issue by tom-vision** [zhangyuanwei/node-images#163]
什么时候能支持node10+

**Comment by xiangshouding** [comment]
最近几天就支持了，需要搭建构建环境，可能稍微慢点。

**Comment by xiangshouding** [comment]
假期把代码写好了，编译了 Mac 上的 10.x 的包，可以在 releases 下载到

tom-vision <notifications@github.com> 于2018年12月29日周六 上午11:40写道：
