### ISSUE TITLE
 images(...).rotate is not a function

### ISSUE THREAD

**Issue by x363090973** [zhangyuanwei/node-images#164]
var images = require("images");
console.log(images)
images("./ceshi.jpg")                                           
    .rotate(45)
    .save("./1.jpg", {               
        quality : 50                    
    });

直接使用.save可以，但是rotate方法不行。。。

**Comment by xiangshouding** [comment]
OK，正在修复

**Comment by x363090973** [comment]
修复了@我下 请你喝果汁~

**Comment by xiangshouding** [comment]
Mac 上已经修复了，直接从 github 安装。

npm install zhangyuanwei/node-images

x363090973 <notifications@github.com> 于2019年1月2日周三 上午9:39写道：

**Comment by x363090973** [comment]
哦  no~ 我的是windows
