### ISSUE TITLE
node 10+ 问题

### ISSUE THREAD

**Issue by dodobaba** [zhangyuanwei/node-images#167]
Mac platform version is 10.14, so the platform equal Darwin.
node version is 10, so equal 64
npm install images the latest version is 3.0.1 
so auto compiles eq darwin-64-64_bind.node
the file in the folder "3.0.2",not in "3.0.1". so will be 404!
the solution is to modify "version:3.0.1" to "version:3.0.2" in the package.json which in the images module folder.
after that manually run "node ./scripts/install.js".
All fine!

**Comment by xiangshouding** [comment]
fixed
