### ISSUE TITLE
Missing bindings for Linux 64-bit with Node.js 8.x

### ISSUE THREAD

**Issue by aybmab** [zhangyuanwei/node-images#170]
When running in AWS lamba (deployed with serverless), I get the following error:

```
images could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
- OS X 64-bit with Unsupported runtime (59)
```

Any chance these bindings could be added?

Thank you in advance!

**Comment by MrPluto** [comment]
#168 `npm rebuild images --force` and i got this 
`Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.2/linux-x64-67_binding.node"`
and seem there has node **x64-67_binding.node** assets?  @xiangshouding

**Comment by xiangshouding** [comment]
#209 
fixed
