### ISSUE TITLE
不能复制图像了

### ISSUE THREAD

**Issue by lanphone** [zhangyuanwei/node-images#174]
images( images("ui.png"), 100,100,177,487).save("ssss.png")
无论x,y设置多少，都是从0,0开始复制

**Comment by 15075767858** [comment]
Image.cc 626行 
之前是
 if(argc == 5) {
        GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[3], &w);
        GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[4], &h);
    }
修改成
 if(argc == 5) {
        GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[1], &x);
        GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[2], &y);
        GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[3], &w);
        GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[4], &h);
    }
重新编译就可以了

**Comment by xiangshouding** [comment]
尴尬，重构的时候漏了，后面补充上 ut

15075767858 <notifications@github.com> 于2019年5月23日周四 上午11:43写道：

**Comment by magicliuu** [comment]
最新版本中，这个问题还是没有解决qwq

我按照上面说的修改了image.cc，但是不懂如何重新编译..是不是还需要我自己有c++/c的环境才可以..

**Comment by GitProQ** [comment]
请问什么时候修复这个问题呐？ 时间长的话 看来要node-gyp重新编译了

**Comment by MrPluto** [comment]
@15075767858 之前是在哪个commit呢

**Comment by gxdyxh** [comment]
> 
> 
> Image.cc 626行
> 之前是
> if(argc == 5) {
> GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[3], &w);
> GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[4], &h);
> }
> 修改成
> if(argc == 5) {
> GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[1], &x);
> GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[2], &y);
> GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[3], &w);
> GET_VALUE_WITH_NAPI_FUNC(napi_get_value_uint32, args[4], &h);
> }
> 重新编译就可以了

PS D:\desktop\node-images-master> node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@10.16.0 | win32 | x64
gyp info find Python using Python version 2.7.17 found at "E:\tool\Python27\python.exe"
gyp info find VS using VS2019 (16.3.29418.71) found at:
gyp info find VS "d:\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn E:\tool\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\gqz\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\desktop\\node-images-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\gqz\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\gqz\\AppData\\Local\\node-gyp\\Cache\\10.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\gqz\\AppData\\Local\\node-gyp\\Cache\\10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\gqz\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\gqz\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\10.16.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\desktop\\node-images-master',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\desktop\\node-images-master\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: gyp\gyp\libpng.gyp not found (cwd: D:\desktop\node-images-master) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\gqz\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "E:\\tool\\nodejs\\node.exe" "C:\\Users\\gqz\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd D:\desktop\node-images-master
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok

**Comment by gxdyxh** [comment]
编译出错
![图片](https://user-images.githubusercontent.com/33820361/68933333-64dc3800-07cf-11ea-8ef9-31d2e4ade1d8.png)
