### ISSUE TITLE
Missing linux-x64-67_binding.node

### ISSUE THREAD

**Issue by nanu-c** [zhangyuanwei/node-images#175]
missing, somehow meteor.com uses them in a docker container. Can you please add them

**Comment by xBeastMode** [comment]
i have this too.
![capture](https://user-images.githubusercontent.com/16060686/53497457-cefa5480-3a69-11e9-99c6-839ca2d27c5f.PNG)

**Comment by MrPluto** [comment]
seems you use a high node version

**Comment by xiangshouding** [comment]
#209
