### ISSUE TITLE
ubuntu 18.04 node 10+ 安装完成，但是运行错

### ISSUE THREAD

**Issue by dodobaba** [zhangyuanwei/node-images#179]
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Node.js v10.15.3

error : 'Segmentation fault (core dumped)'

**Comment by xiangshouding** [comment]
cd  $NODE_PATH/lib
find . -name '*.node'
ldd <node/file/path>.node

贴一下结果我看看

**Comment by dodobaba** [comment]
我已经把node的版本降到8.0+了，先解决用的问题

**Comment by dcarrion87** [comment]
Did you ever get this resolved with Node 10+
I'm having GLIBC compatibility issues on CentOS and Amazon Linux. 
Trying to work out the compilation options now to find out why it's segfaulting when I try to manually compile

**Comment by xiangshouding** [comment]
#209
