### ISSUE TITLE
Windows 64-bit with Unsupported runtime (59)

### ISSUE THREAD

**Issue by yanqiangsjz** [zhangyuanwei/node-images#183]
imagesdoes not yet support your current environment: Windows 64-bit with Unsupported runtime (59)

**Comment by CramericaIndustries** [comment]
@yanqiangsjz same here, did you find a solution?

**Comment by coderForCd** [comment]
@yanqiangsjz @CramericaIndustries 
I also encountered this problem, the nodejs version is too high, downgraded to 10.15

**Comment by xiangshouding** [comment]
#209
