### ISSUE TITLE
对高像素图片(73M)进行压缩时内存增加800M+  (服务器内存1G)是我没设置什么吗

### ISSUE THREAD

**Issue by shenqicheng100** [zhangyuanwei/node-images#189]
var images = require("images");
images.setLimit(99999, 99999)
images.gc()
images("input.jpg"
    .size(800)
    .save("output.jpg", { 
        quality : 50
    });

**Comment by shenqicheng100** [comment]
var images = require("images");
images.setLimit(99999, 99999)
images.gc()
images("input.jpg"
    .size(800)
    .save("output.jpg", { 
        quality : 50
    });

**Comment by shenqicheng100** [comment]
以加处理好了

**Comment by hfutpath** [comment]
> 以加处理好了

大佬，你怎么处理的啊
