### ISSUE TITLE
npm 安装报错404 node版本7.2.0

### ISSUE THREAD

**Issue by 846836199** [zhangyuanwei/node-images#190]

**Comment by 846836199** [comment]
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/win32-x64-51_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

**Comment by lisonge** [comment]
https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/win32-x64-51_binding.node
这个文件它根本不纯在啊

**Comment by xiangshouding** [comment]
#209
