### ISSUE TITLE
在node12环境下报错

### ISSUE THREAD

**Issue by Baiang** [zhangyuanwei/node-images#191]
[Node] Error: imagesdoes not yet support your current environment: OS X 64-bit with Unsupported runtime (72)
[Node] For more information on which environments are supported please see:

**Comment by newlukai** [comment]
Would be great to have these bindings. I would offer my support, but I've never created/compiled bindings.

**Comment by pc1995** [comment]
> [Node] Error: imagesdoes not yet support your current environment: OS X 64-bit with Unsupported runtime (72)
> [Node] For more information on which environments are supported please see:

Hi, how did you solve it？

**Comment by xiangshouding** [comment]
latest version fixed this bug
