### ISSUE TITLE
electron下安装失败

### ISSUE THREAD

**Issue by x363090973** [zhangyuanwei/node-images#192]
在node环境下正常，electron下安装失败， node 10.16.0 32位 ，electron 1.7.5 ,"electron-rebuild": "^1.7.3",

**Comment by g8up** [comment]
@x363090973 请问，怎么解决的？

**Comment by x363090973** [comment]
> @x363090973 请问，怎么解决的？

本来是缺一个旋转功能，自己写了一个dll用来旋转本地图片
