### ISSUE TITLE
cnpm install images 的时候提示下载不了这个 win32-x64-72_binding.node这个文件。怎么办？

### ISSUE THREAD

**Issue by momobeizi** [zhangyuanwei/node-images#198]
Downloading binary from https://github.com/zhangyuanwei/node-images/releases/download/v3.0.2/win32-x64-72_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.2/win32-x64-72_binding.node":

HTTP error 404 Not Found

**Comment by g8up** [comment]
确认下 node 版本是否符合要求

**Comment by momobeizi** [comment]
需要node 什么版本的？我的是V12.12.0版本的node

**Comment by momobeizi** [comment]
> 确认下节点版本是否符合要求
需要node什么版本的？我的是V12.12.0版本的node

**Comment by shencyber** [comment]
不支持node10以上的吧

**Comment by zhengshifei** [comment]
赶紧支持node12啊

**Comment by g8up** [comment]
@momobeizi 
首页文档：
https://github.com/zhangyuanwei/node-images#support-%E6%94%AF%E6%8C%81%E6%83%85%E5%86%B5

**Comment by kevinkenken** [comment]
node_modules/images/vendor/darwin-x64-72 这文件夹内 把darwin-x64-67.binding.node复制进去改名binding.node 就可以使用了 mac上调试不影响

**Comment by xiangshouding** [comment]
#209
