### ISSUE TITLE
请发布一个可以在window系统的node-webkit中使用的编译好的node库吧

### ISSUE THREAD

**Issue by ivygyp** [zhangyuanwei/node-images#20]
我现在需要在自己的node-webkit框架中使用node-images，之前在node中使用非常顺畅和好用，但是采用node-webkit中的nw-gyp进行编译的时候总是出现语法上面的错误提示，无法编译成功，所以恳请作者能够提供一份最新node-webkit框架下window系统的编译后的库。

**Comment by littledu** [comment]
貌似 nw 是有专门提供原生模块的编译的，不能直接使用 node-gyp, 而是要用 nw-gyp： https://github.com/nwjs/nw-gyp
