### ISSUE TITLE
现在linux环境下node版本10还是应用失败的

### ISSUE THREAD

**Issue by smallbad** [zhangyuanwei/node-images#204]
现在linux环境下node版本10还是应用失败的，我看您之前有说更新，想请教一下如何才能在10上应用呢

**Comment by xiangshouding** [comment]
#209

**Comment by freekingg** [comment]
node: symbol lookup error: /app/imagemin/node_modules/images/vendor/linux-x64-binding.node: undefined symbol: reallocarray

centos  node v14.15.1

**Comment by freekingg** [comment]
node: symbol lookup error: /app/imagemin/node_modules/images/vendor/linux-x64-binding.node: undefined symbol: reallocarray

centos  node v14.15.1   我的也不行

**Comment by xiangshouding** [comment]
看上去是 centos 缺乏必要的 so

ldd /app/imagemin/node_modules/images/vendor/linux-x64-binding.node 看输出啥？

记忆的时间差 ***@***.***> 于2021年8月17日周二 下午3:30写道：

**Comment by BigCatGit** [comment]
我也碰到这个问题了，而且是在脚本运行到一半的样子出现，过后就启动不了项目了
