### ISSUE TITLE
ts声明报错了

### ISSUE THREAD

**Issue by yajore** [zhangyuanwei/node-images#225]
node_modules/_images@3.2.3@images/index.d.ts:31:21 - error TS1039: Initializers are not allowed in ambient contexts.

31         fillColor = this.fill;

**Comment by x1n13y84issmd42** [comment]
Having the same issue on TS 4.2.4 and latest `images`. Changing the initializer to a function declaration fixes the problem, but that's not an option for us.

**Comment by x1n13y84issmd42** [comment]
As a workaround for this you can set `skipLibCheck: true` in `tsconfig.json`.

**Comment by yajore** [comment]
3q,the problem has been solved
