### ISSUE TITLE
图片缩放报错

### ISSUE THREAD

**Issue by LaPoPvLe** [zhangyuanwei/node-images#38]
..\src\Image.cc:173 Invalid argumentsArguments error

undefined

//原图
var image = images(path.join('public/upload_temp', paths[0]));
var saveTo = path.resolve(path.join('public/thumbs', path_name));
//试过好几次, 仅宽度报错, 宽度高度也报错, 源码里有个filter, 也不知道是什么类型的, 试了下字符串, 数字, 都报错...
var thumb = image.resize(w, h);

thumb.save(saveTo);

**Comment by 2betop** [comment]
数字，这有 demo 你试试

https://github.com/zhangyuanwei/node-images/blob/master/test/index.js

**Comment by LaPoPvLe** [comment]
不能同时指定高和宽嘛？需求是可能是任何尺寸图变成指定尺寸，不一定是等比的，支持吗？
