### ISSUE TITLE
uncaughtException: Can't load the addon. 

### ISSUE THREAD

**Issue by gkorland** [zhangyuanwei/node-images#42]
I started getting the following error:

``` javascript
{"level":"error","message":"on uncaughtException: Can't load the addon. please try to run `node install.js` command.,\n\nError: Can't load the addon. please try to run `node install.js` command.\n    at Object.<anonymous> (D:\\home\\site\\wwwroot\\node_modules\\images\\binding.js:4:11)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at Object.<anonymous> (D:\\home\\site\\wwwroot\\node_modules\\images\\index.js:4:15)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)","timestamp":"2015-02-15T09:54:39.208Z"}
```

**Comment by xiangshouding** [comment]
Your nodejs version ?

**Comment by gkorland** [comment]
0.10.21

**Comment by gkorland** [comment]
sorry 0.12.0

**Comment by xiangshouding** [comment]
Oh, you just installed?  if not, you  try reinstall. 

 I need to know your system is 32-bit or 64-bit.

**Comment by gkorland** [comment]
Ok, moving back to 0.12.32 fixed it.
I'm running on 32bit

**Comment by xiangshouding** [comment]
oh, you say 0.10.32? 

If your node version has changed, you need to reinstall, because addon is installed when the download version under a particular node version. ( I use google translator. :smile: )

**Comment by gkorland** [comment]
I upgraded to 0.12.0 and reinstall, and got the error.
Then I downgrade back to 0.10.32 and reinstall and it worked.

**Comment by xiangshouding** [comment]
Ok, I recompile, and then re-released, thanks feedback.

**Comment by army8735** [comment]
我在mac上也遇到这个问题，node 0.12
```
throw new Error('Can\'t load the addon. please try to run `node install.js
Error: Can't load the addon. please try to run `node install.js` command.
```

**Comment by xiangshouding** [comment]
重新安装一下

**Comment by xiangshouding** [comment]
如果还是不行把安装打出的显示信息发给我看看。

**Comment by army8735** [comment]
```
npm install images
/
> images@2.1.1 install /Users/army/Sites/sprites/node_modules/images
> (node ./install.js 2> builderror.log) || (exit 0)

Downloading https://raw.githubusercontent.com/zhangyuanwei/node-images/master/bindings/darwin/x64/0.12.0/binding.node
Received 513K...
Received 519K total.
images@2.1.1 node_modules/images
├── step@0.0.5
└── nan@1.6.2
```

**Comment by army8735** [comment]
抱歉，重试了下，发现是在iojs在报的错，nvm弄混了。0.12可以。

**Comment by nitriques** [comment]
@army8735 is io.js support planned ? Building by hand works, but I get 'Module did not self register'

**Comment by ben-eb** [comment]
I'm getting this on Travis CI. https://travis-ci.org/ben-eb/css-minifiers/jobs/57471497

**Comment by xiangshouding** [comment]
@ben-eb can't support  `io.js`

**Comment by nitriques** [comment]
@xiangshouding Why can't you support it ?

**Comment by BearJ** [comment]
node 4.1.1版本又出现了Can't load the addon了。。

**Comment by xiangshouding** [comment]
@BearJ https://github.com/zhangyuanwei/node-images/tree/node-v4.0.0 已经适配完成，但未提供二进制版，后续陆续提供，如果急着用可参考 #45 进行编译。

**Comment by nrkn** [comment]
@xiangshouding can you please add bindings for windows as well?

**Comment by franciscop** [comment]
Node 4.0.0 also cannot load ):

**Comment by nitriques** [comment]
@franciscop node-gyp needs updating. NAN also tu support v4.

**Comment by wufeng87** [comment]
node 1.2.0版本出现了Can't load the addon了

**Comment by xiangshouding** [comment]
node 只有 0.12.0 等版本，并没有 1.2.0 版本。

**Comment by PerttyZhan** [comment]
var images = require('images');
然后就出错了。
C:\zuzuxia\node_modules\images\binding.js:61
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);
^

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-imag
es/issues

我的nodejs版本是5.1.0

**Comment by xiangshouding** [comment]
node 更新太快了 node 5.1.0 并没有支持，等 node 稳定了再适配。@PerttyZhan

**Comment by mattkenefick** [comment]
News?

**Comment by owen-hong** [comment]
/binding.js:61
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);

我的node :6.9.1

**Comment by oliversteiner** [comment]
ERROR:
Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: Cannot find module './bindings/darwin/x64/8.0.0/binding.node'

SETTING:
Node version 8.1.3
macOS 10.12.6 Sierra 
64bit

**Comment by nitriques** [comment]
@oliversteiner would you want to try a build I've made ? it work with the same specs as yours!

**Comment by oliversteiner** [comment]
sure, like to try your build

**Comment by nitriques** [comment]
@oliversteiner cool I am making the build right now.

**Comment by nitriques** [comment]
It will be compiled against the 8.0.0 headers, which should be ok for 8.1.3. If it ever fails, I can show you how to try and build it yourself or I can build against any 8.x versions ;)

**Comment by oliversteiner** [comment]
If it fails, I like to try and build it myself (gather experience).

**Comment by nitriques** [comment]
I do not have the time to write proper docs right now, but heres what you'll need.

node
npm
node-gyp (`npm i-g node-gyp`) 
bash
wget
xcode
python 2.7

```sh
git clone git@github.com:DeuxHuitHuit/node-images.git
cd node-images
git submodule init
git submodule update
cd gyp
./third-party.sh 
cd ..
npm i
npm run rebuild
```

**Comment by oliversteiner** [comment]
ok, i try

**Comment by nitriques** [comment]
Hopefully, all the work I've done to make it simpler to build it won't be in vain!

**Comment by oliversteiner** [comment]
loning into 'node-images'...
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by oliversteiner** [comment]
ok, i've got the git, now trying

**Comment by oliversteiner** [comment]
4 verbose stack Error: missing script: rebuild

**Comment by nitriques** [comment]
are you in the `webp` branch ?

**Comment by nitriques** [comment]
Try `node-gyp rebuild -j 4`

**Comment by oliversteiner** [comment]
i wasnt in the webp branch, sorry, one more try

**Comment by nitriques** [comment]
After that, you can run the tests ;) `npm test`

**Comment by oliversteiner** [comment]
```
git clone  https://github.com/DeuxHuitHuit/node-images.git
cd node-images/
git checkout webp
git submodule init
git submodule update
```

**new Error:**
```
error: Server does not allow request for unadvertised object f72792036d3c92a401fd9ae2f0537f591521671a
Fetched in submodule path 'gyp', but it did not contain f72792036d3c92a401fd9ae2f0537f591521671a. Direct fetching of that commit failed.
```

**Comment by nitriques** [comment]
try this

```sh
cd gyp
git remote origin set-url https://github.com/DeuxHuitHuit/gyp.git
```

**Comment by nitriques** [comment]
and then 

```sh
cd ...
git submodule init
git submodule update
```

**Comment by nitriques** [comment]
(BTW I am having problems updating node on my machine... as soon as this is resolve, I should have a build !)

**Comment by oliversteiner** [comment]
i thick its
git remote **set-url** origin https://github.com/DeuxHuitHuit/gyp.git

**Comment by oliversteiner** [comment]
This sounds familiar, i think it's a problem on my machine.

```
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/png.a] Error 1
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! images@2.2.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the images@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by nitriques** [comment]
Which version of xcode ? and llvm ?

**Comment by oliversteiner** [comment]
```
Xcode : Version 8.3.3 (8E3004b)
Apple LLVM version 8.1.0 (clang-802.0.42)
```

but i think it is a problem with "Homebrew" and / or MAMP

**Comment by oliversteiner** [comment]
a New one:
```

In file included from ../gyp/third-party/libjpeg-turbo/bmp.c:33:
In file included from ../gyp/third-party/libjpeg-turbo/cdjpeg.h:17:
../gyp/third-party/libjpeg-turbo/jinclude.h:23:10: fatal error: 'jconfig.h' file
      not found
#include "jconfig.h"            /* auto configuration options */
         ^
1 error generated.
make: *** [Release/obj.target/libjpeg-turbo/gyp/third-party/libjpeg-turbo/bmp.o] Error 1
Build failed
```

**Comment by oliversteiner** [comment]
I'm stuck at **libjpeg-turbo* 
I deleted all files and retried the build.

`git clone  https://github.com/DeuxHuitHuit/node-images.git
cd node-images/
git checkout webp
git submodule init
git submodule update
cd gyp
git remote set-url origin https://github.com/DeuxHuitHuit/gyp.git
cd ..
git submodule init
git submodule update
cd gyp
chmod +x third-party.sh
./third-party.sh 
cd ..
npm i`

And this is the error:

`In file included from ../gyp/third-party/libjpeg-turbo/bmp.c:33:
In file included from ../gyp/third-party/libjpeg-turbo/cdjpeg.h:17:
../gyp/third-party/libjpeg-turbo/jinclude.h:23:10: fatal error: 'jconfig.h' file
      not found
#include "jconfig.h"            /* auto configuration options */
         ^
1 error generated.
make: *** [Release/obj.target/libjpeg-turbo/gyp/third-party/libjpeg-turbo/bmp.o] Error 1
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! images@2.2.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the images@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by nitriques** [comment]
can you try this:

```sh
cd gyp/third-party/libjpeg-turbo
autoreconf
```

**Comment by oliversteiner** [comment]
same error.
i try another Mac

**Comment by nitriques** [comment]
My build finally started! I'll push a commit soon!

**Comment by nitriques** [comment]
Ah! do you have autotools installed ?

**Comment by nitriques** [comment]
and cmake ?

**Comment by oliversteiner** [comment]
Update:
```
brew install autoconf  automake  cmake

cd gyp/third-party/libjpeg-turbo
sudo autoreconf 
```
same error: 

```../gyp/third-party/libjpeg-turbo/jinclude.h:23:10: fatal error: 'jconfig.h' file  not found
```

**Comment by nitriques** [comment]
Damn. I am afraid it is a problem with your version of xcode then.

I the mean time, here are the new executable for os x, with webp support.

**Comment by nitriques** [comment]
or you can `git pull origin webp`

**Comment by nitriques** [comment]
I have the same error on windows and linux btw ;)

**Comment by nitriques** [comment]
Try this:

```sh
cd ./third-party/libjpeg-turbo
    cmake . || (echo ':MUST: need cmake'; exit 1)
    autoreconf -fiv
    ./configure
cd -
```

Just this. Does it works ?

**Comment by oliversteiner** [comment]
CMake Error at CMakeLists.txt:33 (message):
  Platform not supported by this build system.  Use autotools instead.

**Comment by nitriques** [comment]
Yeah that message is normal ;)
Do what it suggest ;)

```sh
autoreconf -fiv
./configure
```

**Comment by oliversteiner** [comment]
2 other Macs (Macbook and Hackintosh) with same error ()

this is a problem too:

`rm: ./third-party/libwebp/src/utils/random_utils.c: **Permission denied**`

**Comment by nitriques** [comment]
Hum this must because of your `sudo autoreconf`.
You never need sudo to build this.
Try to sudo rm it.

**Comment by oliversteiner** [comment]
fresh install, but same error.

```
git clone  https://github.com/DeuxHuitHuit/node-images.git
cd node-images/
git checkout webp
cd gyp
git remote set-url origin https://github.com/DeuxHuitHuit/gyp.git
cd ..
git submodule init
git submodule update
cd gyp
chmod +x third-party.sh
./third-party.sh 
cd third-party/libjpeg-turbo
autoreconf 
cmake . || (echo ':MUST: need cmake'; exit 1)
./configure
cd ../../../
npm i
```

**Comment by nitriques** [comment]
There is something wrong with your setup, but I can say what.

Did you tried the binaries I've committed ?

**Comment by oliversteiner** [comment]
sorry, im busy, i try mondays

**Comment by nitriques** [comment]
@oliversteiner No stress!!!
