### ISSUE TITLE
nodejs 0.12.0 不能直接用

### ISSUE THREAD

**Issue by yuhowe** [zhangyuanwei/node-images#43]
我的ubuntu服务器安装的是0.12.0的nodejs，直接使用node-images启动不了，找不到.node文件。我也试过在ubuntu编译源码，错误太多过不了，请问能不能提供一个0.12.0的编译好的.node文件，或者告诉我怎么在ubuntu编译，谢谢

**Comment by xiangshouding** [comment]
支持  64 位 Ubuntu，32 位最近正在搞虚拟机，节后放进去。

**Comment by xiangshouding** [comment]
编译方法

  ```cmd
  $ git clone https://github.com/zhangyuanwei/node-images
  $ cd node-images
  $ git submodule init
  $ git submodule update
  $ cd gyp
  $ sh third-party.sh
  $ cd ..
  $ npm install
  $ node-gyp rebuild
  ```

大概四个步骤

- Clone 代码，包括主代码和依赖gyp
- 执行 `sh third-party.sh` 来下载 gyp 用到的所有的源码包，可能会由于墙之类的下载会比较吃力，请自备梯子。
- 安装 `nan` ，`npm install`
- 编译, `node-gyp rebuild`；可能你没有 node-gyp 请安装它 `npm install -g node-gyp`

**Comment by yuhowe** [comment]
按照您说的来操作了
../gyp/third-party/libjpeg-turbo/jinclude.h:22:65: fatal error: jconfig.h: No such file or directory
请问这是缺少什么呢

**Comment by xiangshouding** [comment]
到这个目录`../gyp/third-party/libjpeg-turbo`下去，执行 `cmake`

**Comment by yuhowe** [comment]
非常感谢，已经编译好了！！
