### ISSUE TITLE
不支持最新版本的iojs

### ISSUE THREAD

**Issue by builden** [zhangyuanwei/node-images#46]
提示绑定错误

**Comment by xiangshouding** [comment]
iojs 和 nodejs 说是要合并了，等合并了统一做支持，因为二进制的扩展需要很大的工作量才能搞定，如果想在 iojs 下使用此 package，可能需要你自己编译安装，具体步骤参考 #45 ; iojs 下编译可能有所不同，可参考其他一些相关资料；

**Comment by builden** [comment]
好的，多谢解答

**Comment by mathiasbynens** [comment]
+1 for io.js support!

**Comment by owen-hong** [comment]
![image](https://cloud.githubusercontent.com/assets/6466628/10185967/b8f6005a-677f-11e5-9dac-3b187d989ab6.png)
这次坑爹了，把本地升级到最新版的nodev4.1.1后，Images就报错了，以前一直正常使用

**Comment by xiangshouding** [comment]
那就降级 node，后续会提供 4.0 下的二进制包

**Comment by builden** [comment]
我是来砸场子的，推荐个没有静态依赖的图像处理库
https://www.npmjs.com/package/jimp

**Comment by xiangshouding** [comment]
@builden 感谢，现在版本太低不知道有什么问题，后续调研可以就会引进。我更看重的是 jpeg-js 等基础库
