### ISSUE TITLE
Errors when trying to build bindings 

### ISSUE THREAD

**Issue by xeijix** [zhangyuanwei/node-images#48]
I'm trying to build the bindings from scratch (specifically because i'd like to use node-images in an NW.js project and I need to compile a version for io.js instead of node.js). I'm running into this error when i try to run 'node-gyp build' :

> gyp info it worked if it ends with ok
> gyp info using node-gyp@2.0.1
> gyp info using node@0.10.16 | darwin | x64
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
>  CC(target) Release/obj.target/libjpeg-turbo/gyp/third-party/libjpeg-turbo/bmp.o
> In file included from ../gyp/third-party/libjpeg-turbo/bmp.c:33:
> In file included from ../gyp/third-party/libjpeg-turbo/cdjpeg.h:17:
> ../gyp/third-party/libjpeg-turbo/jpeglib.h:67:9: error: unknown type name 'JSAMPLE'
> typedef JSAMPLE _JSAMPROW;      /_ ptr to one image row of pixel samples. _/
>        ^
> ../gyp/third-party/libjpeg-turbo/jpeglib.h:656:3: error: unknown type name 'JSAMPLE'
>  JSAMPLE \* sample_range_limit; /_ table for fast range-limiting _/
>  ^
> ../gyp/third-party/libjpeg-turbo/bmp.c:128:2: error: use of undeclared identifier 'JPEG_LIB_VERSION'
>        jpeg_create_compress(&cinfo);
>        ^
> ../gyp/third-party/libjpeg-turbo/jpeglib.h:899:34: note: expanded from macro 'jpeg_create_compress'
>    jpeg_CreateCompress((cinfo), JPEG_LIB_VERSION, \
>                                 ^
> ../gyp/third-party/libjpeg-turbo/bmp.c:168:17: warning: incompatible pointer types passing 'JSAMPROW' (aka 'int *') to parameter of type 'unsigned char *' [-Wincompatible-pointer-types]
>                        pixelconvert(src->buffer[i], srcpf, 0, outbuf, dstpf, bottomup, *w,
>                                     ^~~~~~~~~~~~~~
> ../gyp/third-party/libjpeg-turbo/bmp.c:75:41: note: passing argument to parameter 'srcbuf' here
> static void pixelconvert(unsigned char *srcbuf, int srcpf, int srcbottomup,
>                                        ^
> ../gyp/third-party/libjpeg-turbo/bmp.c:212:2: error: use of undeclared identifier 'JPEG_LIB_VERSION'
>        jpeg_create_decompress(&dinfo);
>        ^
> ../gyp/third-party/libjpeg-turbo/jpeglib.h:902:36: note: expanded from macro 'jpeg_create_decompress'
>    jpeg_CreateDecompress((cinfo), JPEG_LIB_VERSION, \
>                                   ^
> ../gyp/third-party/libjpeg-turbo/bmp.c:256:41: warning: incompatible pointer types passing 'JSAMPROW' (aka 'int *') to parameter of type 'unsigned char *' [-Wincompatible-pointer-types]
>                        pixelconvert(inbuf, srcpf, bottomup, dst->buffer[i], dstpf, 0, w,
>                                                             ^~~~~~~~~~~~~~
> ../gyp/third-party/libjpeg-turbo/bmp.c:76:17: note: passing argument to parameter 'dstbuf' here
>        unsigned char *dstbuf, int dstpf, int dstbottomup, int w, int h)
>                       ^
> 2 warnings and 4 errors generated.
> make: *_\* [Release/obj.target/libjpeg-turbo/gyp/third-party/libjpeg-turbo/bmp.o] Error 1

Note: I've tried running it with node-gyp and nw-gyp just to be sure it's not because of nw-gyp.
Have you ever encountered this sort of error when trying to compile libjpeg-turbo?
I'm trying to compile this for OSX v10.10.3 x64 if that helps

**Comment by xiangshouding** [comment]
编译前请安装 cmake
