### ISSUE TITLE
有没有获取 Base64 数据的接口

### ISSUE THREAD

**Issue by Manjiz** [zhangyuanwei/node-images#62]
图片处理之后，我不想保存到文件，而是想获取一段base64数据。

**Comment by hungchai** [comment]
Just seen your question, Nodejs has built-in function to do this.

var toBase64 = imgbuffer.toString('base64');

**Comment by Manjiz** [comment]
@hungchai Thanks a lot. I found this. So I do not need to save the img file first.
> .encode(type[, config])
> eg:images("input.png").encode("jpg", {operation:50}) Encode image to buffer, config is image setting.
以指定格式编码当前图像到Buffer，config为图片设置，目前支持设置JPG图像质量
Return buffer
> 返回填充好的Buffer

And code `.encode("jpg", {operation:50}).toString('base64'))`
