### ISSUE TITLE
Can't load the addon.

### ISSUE THREAD

**Issue by myfmyy** [zhangyuanwei/node-images#69]
\node_modules.npminstall\images\2.1.11\images\binding.js:61

**Comment by myfmyy** [comment]
重装Nodejs 4.4.0解决了。5.0以后版本替换binding.node也没用

**Comment by jinghaonode** [comment]
win7-64        node 5.10  出现同样问题， 只因前几天升级node的版本

**Comment by xiangshouding** [comment]
5.0 API 更新的比较奇葩，暂时还没有适配

**Comment by superlc** [comment]
我的5.0.X版本，也遇到了这个问题，求早日fix
