### ISSUE TITLE
什么时候添加6.X支持啊！

### ISSUE THREAD

**Issue by klwu** [zhangyuanwei/node-images#73]
如题

**Comment by xiangshouding** [comment]
快了
2016年5月1日 下午3:34，"xiaowu" <notifications@github.com>写道：

**Comment by sp42** [comment]
不错，加油哦

**Comment by xiangshouding** [comment]
https://github.com/zhangyuanwei/node-images/tree/node-v6.0.0

Mac 已经提供二进制包，其他平台急用请自己编译；
