### ISSUE TITLE
Uncaught Error: Can't load the addon.

### ISSUE THREAD

**Issue by chengaomin** [zhangyuanwei/node-images#75]
试了node 5.x和6.x，都会这样。求帮助啊
\node_modules\images\binding.js:61 Uncaught Error: Can't load the addon.

**Comment by sp42** [comment]
v4.4.4 Centos v6.7 Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/zhangxin/node4/bin/node_modules/images/bindings/linux/x64/4.0.0/binding.node)

**Comment by xiangshouding** [comment]
改 library_path 吧，不过此类问题解决起来蛮麻烦的。

**Comment by xiangshouding** [comment]
可能最后还是得自己编译一把

**Comment by sp42** [comment]
是的
自己编译
根据 http://www.cnblogs.com/wxpjimmy/p/4018718.html 这里的一步步走

**Comment by yaoleo** [comment]
楼上大大们是怎么解决的？！
