### ISSUE TITLE
var images = require('images'); fails, but just  require('images') is Ok

### ISSUE THREAD

**Issue by sp42** [zhangyuanwei/node-images#76]
First, Win32 is fine, no probelm.
However, in Centos 6.7 64bit / glbic2.14, the same code, If I use"
`var images = require('images');`
the request to send are failed, even the simplest HEAD reqeust:
`   

    var images = require("images");  // using node-images in var
    var http = require("http"), url = require("url");  
    var siteUrl = url.parse('http://img1.gtimg.com/view/pics/hv1/42/80/2065/134297067.jpg');  

    var request = http.request({  
        method : 'HEAD',  
        port: siteUrl.port || 80,  
        host: siteUrl.host,  
        path : siteUrl.pathname  
    });  
    request.on('response', function (response) {  
        response.setEncoding('utf8');  
        console.log(response.headers['content-length']);  
    });  
    request.end();  `
No exception is thrown, just timeout of the reqeust.
so I tried to remove  var images = require('images'); , is ok, and using require('images').xx().xx() is also ok.
So What happened?
咋回事呢？var images = require('images');  这样子就发不出请求，不赋予变量的话就可以。。。

**Comment by xiangshouding** [comment]
@sp42 估计 images 无法支持你的系统，这段代码挂了。

**Comment by sp42** [comment]
可是不赋予变量就可以，，能支持的，，有点奇怪
