### ISSUE TITLE
为什么图片体积反而变大了一倍？

### ISSUE THREAD

**Issue by wodog** [zhangyuanwei/node-images#82]
没有做任何压缩处理，保存的图片体积是之前的一倍
```
images('./a.jpg').save('output.jpg');
```

**Comment by zhangyuanwei** [comment]
因为 images 读取图片的时候是将图片解码成RGBA像素，而生成图片的时候是将RGBA像素编码成对应格式，生成 jpg 时默认的 quality 参数为 100。

**Comment by wodog** [comment]
quality参数为100, 为什么输出的不是原图的体积大小，反而体积大了更多了？
我想要保持原图的体积大小该怎么做？
