### ISSUE TITLE
PNG resize antialiasing

### ISSUE THREAD

**Issue by sta-ger** [zhangyuanwei/node-images#84]
Hi! I'm trying to resize a transparent PNG image like this one:
![image](https://cloud.githubusercontent.com/assets/8860947/16565267/7d7e0a1e-420c-11e6-9734-d40ba2f55813.png)

 I'm doing:

var img = images(filePath);
img.resize(newWidth, newHeight);
img.save(filePath);

As a result I have an ugly image with ragged borders.
![image](https://cloud.githubusercontent.com/assets/8860947/16565227/3c6780c8-420c-11e6-9359-6059cdaf391c.png)

Am I doing something wrong or is it a bug in node-images?

**Comment by amcs99** [comment]
anyone has solutions for this? I'm still have trouble with this problem

**Comment by amcs99** [comment]
Did this problem solve? I'm still got trouble with it when resize image.

**Comment by amcs99** [comment]
Is this problem solved? I'm still got trouble with it when resize image.
