### ISSUE TITLE
How to keep image1 and image2 side by side and save it in another image?

### ISSUE THREAD

**Issue by DakshayaniChebrolu** [zhangyuanwei/node-images#92]
Hi

I have two images ... image1, image2

I want to keep those two images in side by side and save it as a image3.

Please tell me the way to do using images.

**Comment by DakshayaniChebrolu** [comment]
Please any one reply to my query...

**Comment by xiangshouding** [comment]
yeah,  you can  use `.draw()`

**Comment by DakshayaniChebrolu** [comment]
Thanks,but i am not getting my output properly

images("image2.png")
    .draw(images("image1.png"). 0, 0)
    .save("image3.jpg", {
        quality: 50
    });

Can you please elaborate.

**Comment by DakshayaniChebrolu** [comment]
Please help me the way to proceed further

**Comment by likang19870916** [comment]
why not use a bg.png which fill with #fffff; then images("bg.png").draw(images("image1.png"),0,0).draw(images("image2.png"),image1.width,0).save("image3.png");
