### ISSUE TITLE
Can't load the addon

### ISSUE THREAD

**Issue by dinfyru** [zhangyuanwei/node-images#94]
```
Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/var/www/revizor-game.ru/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/revizor-game.ru/node_modules/images/index.js:32:15)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
error: Forever detected script exited with code: 1
error: Script restart attempt #1

```
Node -v 7.0.0
debian 8 x64
English plz

**Comment by Dinfyru** [comment]
try node-gyp configure 
```
/node_modules/images# node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.29 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/revizor-game.ru/node_modules/images/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dmodule_root_dir=/var/www/revizor-game.ru/node_modules/images',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: gyp/gyp/libpng.gyp not found (cwd: /var/www/revizor-game.ru/node_modules/images) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "configure"
gyp ERR! cwd /var/www/revizor-game.ru/node_modules/images
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok

```

**Comment by danielmcconville** [comment]
Hey @Dinfyru 

I was having the same problem. I took a look at the code and there are only a set number of supported node version bindings:

./bindings/darwin/x64/0.12.0/binding.node
./bindings/darwin/x64/0.8.0/binding.node
./bindings/darwin/x64/0.9.11/binding.node
./bindings/darwin/x64/4.0.0/binding.node
./bindings/darwin/x64/5.0.0/binding.node
./bindings/darwin/x64/6.0.0/binding.node
./bindings/linux/ia32/0.12.0/binding.node
./bindings/linux/ia32/0.8.0/binding.node
./bindings/linux/ia32/0.9.11/binding.node
./bindings/linux/ia32/4.0.0/binding.node
./bindings/linux/ia32/5.0.0/binding.node
./bindings/linux/ia32/6.0.0/binding.node
./bindings/linux/x64/0.12.0/binding.node
./bindings/linux/x64/0.8.0/binding.node
./bindings/linux/x64/0.9.11/binding.node
./bindings/linux/x64/4.0.0/binding.node
./bindings/linux/x64/5.0.0/binding.node
./bindings/linux/x64/6.0.0/binding.node
./bindings/win32/ia32/0.12.0/binding.node
./bindings/win32/ia32/0.8.0/binding.node
./bindings/win32/ia32/0.9.11/binding.node
./bindings/win32/ia32/4.0.0/binding.node
./bindings/win32/ia32/5.0.0/binding.node
./bindings/win32/ia32/6.0.0/binding.node
./bindings/win32/x64/0.12.0/binding.node
./bindings/win32/x64/0.8.0/binding.node
./bindings/win32/x64/0.9.11/binding.node
./bindings/win32/x64/4.0.0/binding.node
./bindings/win32/x64/5.0.0/binding.node
./bindings/win32/x64/6.0.0/binding.node

You basically need to be running a node version that is specified in the above bindings, for the platform you are running it on. 

For example:

**./bindings/win32/x64/6.0.0/binding.node** - means node v6.0.0 is supported on 64bit win platforms
**./bindings/win32/ia32/5.0.0/binding.node** - means node v5.0.0 is supported on 32bit win platforms

Or at least I think that is how this is working ;)

Anyway, I was running 7.x.x on a Windows Azure platform, which is not in the above list. So I have changed my version to 6.0.0 and it has resolved the issue.

It looks like you are running on linux, so take a look at the version for linux or dawin.

Hope that helps.

**Comment by Dinfyru** [comment]
@danielmcconville i use NVM for change node version, and i fix it

**Comment by DidoFitch** [comment]
@danielmcconville it's very useful!thanks!from this problem  i got that i can't solve any problem if i don't konw the source code
