### ISSUE TITLE
glibc 2.5 能支持的不？

### ISSUE THREAD

**Issue by justnewbee** [zhangyuanwei/node-images#99]
linux x64 机器上要求 glibc2.14 但出于某些原因无法升级 上面的 glibc 版本是 2.5 能支持的吗

**Comment by xiangshouding** [comment]
你可以 copy 一份能跑的 glib2.14 然后在运行前设置环境变量

export LD_LIBRARY_PATH=你放glib2.14的目录

当然如果缺少别的什么东西，一并 copy 过来即可。

**Comment by justnewbee** [comment]
有些难度... 能支持到 GLIBC_2.12 吗 我的服务器现在版本 GLIBC_2.12
我看了 bindings.node 中写了 GLIBC_2.2.5 GLIBC_2.14 GLIBC_2.4 GLIBC_2.7 GLIBC_2.3.4 GLIBC_2.11 GLIBCXX_3.4 这些 必须是特定版本号的话实在有些蛋疼

**Comment by justnewbee** [comment]
而且我试了自己构建 glibc_2.14 构建没有什么问题 最终执行的时候 确实没有报错 但似乎卡住了 进程没有继续

**Comment by xiangshouding** [comment]
卡住，是不是图片太大导致。

**Comment by justnewbee** [comment]
不是 是项目启动的时候卡住不动 也没有报错

**Comment by justnewbee** [comment]
应该是执行 `npm install` 就会死住不动
